import re
import sys
import os

def apply_dark_mode(filepath):
    """
    Reads an HTML file generated with light-mode Material Design Tailwind classes
    and injects the appropriate dark mode utility classes.
    """
    if not os.path.exists(filepath):
        print(f"Error: File '{filepath}' not found.")
        return

    with open(filepath, "r", encoding="utf-8") as f:
        html = f.read()

    # Dictionary mapping light classes to their dark-mode augmented versions
    replacements = {
        'bg-background': 'bg-background dark:bg-slate-900',
        'text-on-background': 'text-on-background dark:text-slate-100',
        'bg-surface-container-lowest': 'bg-surface-container-lowest dark:bg-slate-800',
        'bg-surface-container-low': 'bg-surface-container-low dark:bg-slate-700/50',
        'bg-surface-container-high': 'bg-surface-container-high dark:bg-slate-700',
        'bg-surface-container-highest': 'bg-surface-container-highest dark:bg-slate-600',
        'bg-surface-container': 'bg-surface-container dark:bg-slate-800/80',
        'bg-surface-dim': 'bg-surface-dim dark:bg-slate-800',
        'bg-surface': 'bg-surface dark:bg-slate-900',
        'text-on-surface-variant': 'text-on-surface-variant dark:text-slate-300',
        'text-on-surface': 'text-on-surface dark:text-slate-100',
        'border-outline-variant': 'border-outline-variant dark:border-slate-600',
        'text-secondary': 'text-secondary dark:text-slate-400',
        'hover:text-primary': 'hover:text-primary dark:hover:text-white',
        'bg-surface/80': 'bg-surface/80 dark:bg-slate-900/80',
        'text-primary': 'text-primary dark:text-blue-300',
        'bg-primary-container': 'bg-primary-container dark:bg-blue-600',
        'text-on-primary': 'text-on-primary dark:text-white',
        'hover:bg-primary': 'hover:bg-primary dark:hover:bg-blue-500',
        'hover:bg-surface-container-lowest': 'hover:bg-surface-container-lowest dark:hover:bg-slate-700',
        'hover:bg-surface': 'hover:bg-surface dark:hover:bg-slate-800',
        'ring-background': 'ring-background dark:ring-slate-900'
    }

    # Remove any broken/incomplete dark mode classes generated by the template
    bad_dark_classes = [
        'dark:bg-surface-dim/80',
        'dark:border-on-surface-variant',
        'dark:text-on-primary-fixed',
        'dark:text-secondary-fixed-dim',
        'dark:hover:text-primary-fixed-dim',
        'dark:hover:bg-surface-container-highest',
        'dark:text-primary-fixed-dim',
        'dark:bg-on-primary-fixed'
    ]
    for bad in bad_dark_classes:
        html = html.replace(' ' + bad, '')

    # Sort keys by length (longest first) to prevent substring overlap bugs!
    # This prevents 'text-on-surface' from accidentally replacing part of 'text-on-surface-variant'
    sorted_keys = sorted(replacements.keys(), key=len, reverse=True)
    
    for k in sorted_keys:
        v = replacements[k]
        
        # Use regex to replace exact class matches
        # Negative lookbehind and lookahead ensure we match exact class boundaries (including : and /)
        escaped_k = re.escape(k)
        pattern = r'(?<![-a-zA-Z0-9:/])' + escaped_k + r'(?![-a-zA-Z0-9:/])'
        
        # Make the script idempotent (running it multiple times won't duplicate dark tags)
        # We only replace if the target value isn't already present in that exact spot.
        # Since we use simple replacing, we can just replace the key with the value, 
        # but to avoid 'class="... dark:bg-slate-900 dark:bg-slate-900"', we do a check:
        # We'll just replace the existing class, but first we can strip out 'v' if it was added, or just rely on a regex
        # A simpler way to be idempotent: strip the dark class if it exists, then add it back.
        
        # Let's just remove the dark class part first in case it's there
        dark_class = v.replace(k + " ", "")
        html = html.replace(f"{k} {dark_class}", k)
        
        # Now apply the replacement safely
        html = re.sub(pattern, v, html)
            
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
        
    print(f"Successfully processed {filepath} for dark mode!")

if __name__ == "__main__":
    # If run with a filename argument, process that file. Otherwise default to code.html
    target_file = sys.argv[1] if len(sys.argv) > 1 else "code.html"
    apply_dark_mode(target_file)
